import "dotenv/config";
import { PrismaNeon } from "@prisma/adapter-neon";
import { PrismaClient } from "../src/generated/prisma/client";

async function main() {
  const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL! });
  const prisma = new PrismaClient({ adapter });

  const sources = await prisma.listingSource.findMany();
  const sourceMap = Object.fromEntries(sources.map((s) => [s.slug, s.id]));

  const listings = [
    // === AUSTIN OFFICE ===
    {
      address: "100 Congress Ave",
      city: "Austin",
      zip: "78701",
      lat: 30.2649,
      lng: -97.7453,
      market: "austin",
      propertyType: "Office",
      listingType: "Lease",
      buildingSf: 45000,
      priceAmount: 42,
      priceUnit: "per_sf_yr",
      yearBuilt: 2018,
      brokerName: "Sarah Mitchell",
      brokerCompany: "CBRE",
      description: "Class A office space in the heart of downtown Austin. Floor-to-ceiling windows with Capitol views. Recently renovated lobby and common areas.",
      imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600",
      sourceSlug: "loopnet",
      externalId: "LN-AUS-001",
      sourceUrl: "https://loopnet.com/listing/100-congress",
    },
    {
      address: "200 Barton Springs Rd",
      city: "Austin",
      zip: "78704",
      lat: 30.2610,
      lng: -97.7540,
      market: "austin",
      propertyType: "Office",
      listingType: "Lease",
      buildingSf: 12500,
      priceAmount: 38,
      priceUnit: "per_sf_yr",
      yearBuilt: 2015,
      brokerName: "James Chen",
      brokerCompany: "JLL",
      description: "Modern creative office near Zilker Park. Open floor plan with exposed brick and polished concrete floors. Walking distance to South Lamar dining.",
      imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600",
      sourceSlug: "crexi",
      externalId: "CX-AUS-001",
      sourceUrl: "https://crexi.com/properties/200-barton-springs",
    },
    {
      address: "11501 Domain Dr",
      city: "Austin",
      zip: "78758",
      lat: 30.4021,
      lng: -97.7253,
      market: "austin",
      propertyType: "Office",
      listingType: "Lease",
      buildingSf: 85000,
      priceAmount: 48,
      priceUnit: "per_sf_yr",
      yearBuilt: 2020,
      brokerName: "Michael Torres",
      brokerCompany: "Cushman & Wakefield",
      description: "Trophy office tower in The Domain. LEED Platinum certified. Amenity-rich with fitness center, conference facilities, and rooftop terrace.",
      imageUrl: "https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=600",
      sourceSlug: "realtor",
      externalId: "RE-AUS-001",
    },
    {
      address: "3700 N Capital of Texas Hwy",
      city: "Austin",
      zip: "78746",
      lat: 30.3590,
      lng: -97.7970,
      market: "austin",
      propertyType: "Office",
      listingType: "Sale",
      buildingSf: 32000,
      priceAmount: 8500000,
      priceUnit: "total",
      yearBuilt: 2005,
      brokerName: "Robert Davison",
      brokerCompany: "Davison & Vogel",
      description: "Westlake office building with hill country views. 92% occupied with strong tenant mix. Value-add opportunity with below-market rents.",
      imageUrl: "https://images.unsplash.com/photo-1577495508048-b635879837f1?w=600",
      sourceSlug: "davisonvogel",
      externalId: "DV-AUS-001",
    },
    // === AUSTIN RETAIL ===
    {
      address: "1200 S Lamar Blvd",
      city: "Austin",
      zip: "78704",
      lat: 30.2525,
      lng: -97.7671,
      market: "austin",
      propertyType: "Retail",
      listingType: "Lease",
      buildingSf: 3200,
      priceAmount: 32,
      priceUnit: "per_sf_yr",
      yearBuilt: 2012,
      brokerName: "Lisa Park",
      brokerCompany: "Marcus & Millichap",
      description: "Prime South Lamar retail space with excellent street visibility. High traffic count of 35,000+ vehicles daily. Adjacent to popular restaurants.",
      imageUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600",
      sourceSlug: "loopnet",
      externalId: "LN-AUS-002",
    },
    {
      address: "10000 Research Blvd",
      city: "Austin",
      zip: "78759",
      lat: 30.3873,
      lng: -97.7480,
      market: "austin",
      propertyType: "Retail",
      listingType: "Sale",
      buildingSf: 22000,
      lotSizeAcres: 1.8,
      priceAmount: 5200000,
      priceUnit: "total",
      yearBuilt: 1998,
      brokerName: "David Hernandez",
      brokerCompany: "CBRE",
      description: "Multi-tenant retail strip center on Research Blvd. 95% occupied. NNN leases with annual escalations. Strong demographics within 3-mile radius.",
      imageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=600",
      sourceSlug: "crexi",
      externalId: "CX-AUS-002",
    },
    // === AUSTIN INDUSTRIAL ===
    {
      address: "4500 E Ben White Blvd",
      city: "Austin",
      zip: "78741",
      lat: 30.2280,
      lng: -97.7100,
      market: "austin",
      propertyType: "Industrial",
      listingType: "Lease",
      buildingSf: 65000,
      lotSizeAcres: 4.2,
      priceAmount: 14,
      priceUnit: "per_sf_yr",
      yearBuilt: 2019,
      brokerName: "Kevin Wu",
      brokerCompany: "Prologis",
      description: "Modern distribution warehouse with 32' clear height. 8 dock-high doors, 2 drive-in doors. ESFR sprinkler system. Immediate access to SH 71.",
      imageUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600",
      sourceSlug: "realtor",
      externalId: "RE-AUS-002",
    },
    {
      address: "9200 E Hwy 290",
      city: "Austin",
      zip: "78724",
      lat: 30.3050,
      lng: -97.6340,
      market: "austin",
      propertyType: "Industrial",
      listingType: "Sale",
      buildingSf: 120000,
      lotSizeAcres: 8.5,
      priceAmount: 16800000,
      priceUnit: "total",
      yearBuilt: 2021,
      brokerName: "Amanda Foster",
      brokerCompany: "Colliers",
      description: "State-of-the-art logistics facility near Austin-Bergstrom corridor. Cross-dock configuration. Fully climate controlled. Tesla Gigafactory nearby.",
      imageUrl: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=600",
      sourceSlug: "loopnet",
      externalId: "LN-AUS-003",
    },
    // === AUSTIN MULTIFAMILY ===
    {
      address: "2400 E Riverside Dr",
      city: "Austin",
      zip: "78741",
      lat: 30.2390,
      lng: -97.7250,
      market: "austin",
      propertyType: "Multifamily",
      listingType: "Sale",
      buildingSf: 180000,
      lotSizeAcres: 5.0,
      priceAmount: 42000000,
      priceUnit: "total",
      yearBuilt: 2016,
      brokerName: "Patricia Reynolds",
      brokerCompany: "Newmark",
      description: "240-unit Class A apartment community on East Riverside. Resort-style pool, fitness center, and dog park. 96% occupancy. Strong rent growth submarket.",
      imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600",
      sourceSlug: "crexi",
      externalId: "CX-AUS-003",
    },
    // === AUSTIN LAND ===
    {
      address: "15800 FM 1826",
      city: "Austin",
      zip: "78737",
      lat: 30.2050,
      lng: -97.8780,
      market: "austin",
      propertyType: "Land",
      listingType: "Sale",
      lotSizeAcres: 45.0,
      priceAmount: 9000000,
      priceUnit: "total",
      yearBuilt: null,
      brokerName: "Tom Bradley",
      brokerCompany: "Land Advisors",
      description: "45-acre development tract in Dripping Springs ETJ. Zoned for mixed-use. Rolling topography with mature oaks. Preliminary site plan for 200+ residential lots.",
      sourceSlug: "davisonvogel",
      externalId: "DV-AUS-002",
    },

    // === DFW OFFICE ===
    {
      address: "2200 Ross Ave",
      city: "Dallas",
      zip: "75201",
      lat: 32.7890,
      lng: -96.7980,
      market: "dfw",
      propertyType: "Office",
      listingType: "Lease",
      buildingSf: 72000,
      priceAmount: 35,
      priceUnit: "per_sf_yr",
      yearBuilt: 2017,
      brokerName: "Greg Younger",
      brokerCompany: "Younger Partners",
      description: "Class A high-rise office in Dallas Arts District. Panoramic skyline views. On-site parking garage. Walking distance to DART rail and Klyde Warren Park.",
      imageUrl: "https://images.unsplash.com/photo-1464938050520-ef2571e6f5af?w=600",
      sourceSlug: "youngerpartners",
      externalId: "YP-DFW-001",
    },
    {
      address: "5400 Legacy Dr",
      city: "Plano",
      zip: "75024",
      lat: 33.0760,
      lng: -96.8190,
      market: "dfw",
      propertyType: "Office",
      listingType: "Lease",
      buildingSf: 55000,
      priceAmount: 30,
      priceUnit: "per_sf_yr",
      yearBuilt: 2019,
      brokerName: "Jennifer Adams",
      brokerCompany: "Stream Realty",
      description: "Class A office campus in Legacy business park. Full-floor availability. Amenity center with conference rooms, café, and outdoor workspace.",
      imageUrl: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=600",
      sourceSlug: "loopnet",
      externalId: "LN-DFW-001",
    },
    {
      address: "777 Main St",
      city: "Fort Worth",
      zip: "76102",
      lat: 32.7555,
      lng: -97.3308,
      market: "dfw",
      propertyType: "Office",
      listingType: "Sale",
      buildingSf: 140000,
      priceAmount: 28000000,
      priceUnit: "total",
      yearBuilt: 2001,
      brokerName: "Mark Sullivan",
      brokerCompany: "HFF",
      description: "Landmark downtown Fort Worth office tower. Recently renovated. 88% leased to credit tenants. Strong cash flow with upside through lease-up.",
      imageUrl: "https://images.unsplash.com/photo-1486718448742-163732cd1544?w=600",
      sourceSlug: "crexi",
      externalId: "CX-DFW-001",
    },
    {
      address: "3100 Olympus Blvd",
      city: "Dallas",
      zip: "75019",
      lat: 32.9930,
      lng: -96.8280,
      market: "dfw",
      propertyType: "Office",
      listingType: "Sublease",
      buildingSf: 28000,
      priceAmount: 22,
      priceUnit: "per_sf_yr",
      yearBuilt: 2020,
      brokerName: "Rachel Kim",
      brokerCompany: "Younger Partners",
      description: "Sublease opportunity in Cypress Waters. Fully built-out with modern finishes. Furniture negotiable. Below-market rate. Term through 2028.",
      imageUrl: "https://images.unsplash.com/photo-1497215842964-222b430dc094?w=600",
      sourceSlug: "youngerpartners",
      externalId: "YP-DFW-002",
    },
    // === DFW RETAIL ===
    {
      address: "8500 Preston Rd",
      city: "Dallas",
      zip: "75225",
      lat: 32.8670,
      lng: -96.8010,
      market: "dfw",
      propertyType: "Retail",
      listingType: "Lease",
      buildingSf: 4800,
      priceAmount: 45,
      priceUnit: "per_sf_yr",
      yearBuilt: 2010,
      brokerName: "Chris O'Brien",
      brokerCompany: "Weitzman",
      description: "Upscale retail space in Preston Center. Adjacent to NorthPark Center. High household income demographics. Ideal for restaurant or boutique concept.",
      imageUrl: "https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?w=600",
      sourceSlug: "loopnet",
      externalId: "LN-DFW-002",
    },
    {
      address: "4200 W Park Blvd",
      city: "Plano",
      zip: "75093",
      lat: 33.0340,
      lng: -96.7690,
      market: "dfw",
      propertyType: "Retail",
      listingType: "Sale",
      buildingSf: 35000,
      lotSizeAcres: 3.2,
      priceAmount: 7800000,
      priceUnit: "total",
      yearBuilt: 2008,
      brokerName: "Daniel Wright",
      brokerCompany: "Marcus & Millichap",
      description: "Grocery-anchored neighborhood center in West Plano. 97% leased. Strong tenant mix including national credit tenants. 6.2% cap rate.",
      imageUrl: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=600",
      sourceSlug: "realtor",
      externalId: "RE-DFW-001",
    },
    // === DFW INDUSTRIAL ===
    {
      address: "1000 Westport Pkwy",
      city: "Fort Worth",
      zip: "76177",
      lat: 32.9120,
      lng: -97.3140,
      market: "dfw",
      propertyType: "Industrial",
      listingType: "Lease",
      buildingSf: 250000,
      lotSizeAcres: 15.0,
      priceAmount: 8.50,
      priceUnit: "per_sf_yr",
      yearBuilt: 2022,
      brokerName: "Steve Martinez",
      brokerCompany: "CBRE",
      description: "Mega-distribution facility in AllianceTexas. 40' clear height. 50 dock doors. 185' truck court. BNSF intermodal access within 5 miles.",
      imageUrl: "https://images.unsplash.com/photo-1565610222536-ef125c59da2e?w=600",
      sourceSlug: "crexi",
      externalId: "CX-DFW-002",
    },
    {
      address: "2800 E Piano Pkwy",
      city: "Arlington",
      zip: "76011",
      lat: 32.7350,
      lng: -97.0860,
      market: "dfw",
      propertyType: "Industrial",
      listingType: "Sale",
      buildingSf: 95000,
      lotSizeAcres: 6.0,
      priceAmount: 12500000,
      priceUnit: "total",
      yearBuilt: 2020,
      brokerName: "William Zhang",
      brokerCompany: "Lee & Associates",
      description: "Class A industrial building in Great Southwest submarket. 36' clear height. T-5 lighting. ESFR sprinklers. Divisible to 45,000 SF.",
      imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600",
      sourceSlug: "loopnet",
      externalId: "LN-DFW-003",
    },
    // === DFW MULTIFAMILY ===
    {
      address: "3500 McKinney Ave",
      city: "Dallas",
      zip: "75204",
      lat: 32.8050,
      lng: -96.7970,
      market: "dfw",
      propertyType: "Multifamily",
      listingType: "Sale",
      buildingSf: 220000,
      lotSizeAcres: 3.5,
      priceAmount: 55000000,
      priceUnit: "total",
      yearBuilt: 2018,
      brokerName: "Elizabeth Turner",
      brokerCompany: "Newmark",
      description: "300-unit luxury apartment tower in Uptown Dallas. Sky lounge, infinity pool, valet parking. Average rent $2,400/month. Walk score 92.",
      imageUrl: "https://images.unsplash.com/photo-1567496898669-ee935f5f647a?w=600",
      sourceSlug: "realtor",
      externalId: "RE-DFW-002",
    },
    // === DFW LAND ===
    {
      address: "FM 720 & US 380",
      city: "Prosper",
      zip: "75078",
      lat: 33.2360,
      lng: -96.8010,
      market: "dfw",
      propertyType: "Land",
      listingType: "Sale",
      lotSizeAcres: 80.0,
      priceAmount: 18000000,
      priceUnit: "total",
      yearBuilt: null,
      brokerName: "Andrew Patterson",
      brokerCompany: "Younger Partners",
      description: "80-acre master-planned development site at major intersection in booming Prosper. Town-approved PD zoning for 600+ residential lots and 15 acres of commercial.",
      sourceSlug: "youngerpartners",
      externalId: "YP-DFW-003",
    },
    // === MORE MIXED TYPES ===
    {
      address: "600 W 6th St",
      city: "Austin",
      zip: "78701",
      lat: 30.2700,
      lng: -97.7490,
      market: "austin",
      propertyType: "Mixed Use",
      listingType: "Sale",
      buildingSf: 42000,
      lotSizeAcres: 0.5,
      priceAmount: 15000000,
      priceUnit: "total",
      yearBuilt: 2017,
      brokerName: "Nicole Ramirez",
      brokerCompany: "Transwestern",
      description: "Mixed-use building in West 6th District. Ground-floor retail with 3 floors of office above. Rooftop deck. 100% leased. Strong live-work-play location.",
      imageUrl: "https://images.unsplash.com/photo-1460317442991-0ec209397118?w=600",
      sourceSlug: "loopnet",
      externalId: "LN-AUS-004",
    },
    {
      address: "1800 Main St",
      city: "Dallas",
      zip: "75201",
      lat: 32.7830,
      lng: -96.7990,
      market: "dfw",
      propertyType: "Mixed Use",
      listingType: "Lease",
      buildingSf: 18000,
      priceAmount: 28,
      priceUnit: "per_sf_yr",
      yearBuilt: 2015,
      brokerName: "Brian Calloway",
      brokerCompany: "Younger Partners",
      description: "Street-level retail and second-floor office in Main Street District. Open layout. Floor-to-ceiling glass storefront. High pedestrian traffic.",
      imageUrl: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=600",
      sourceSlug: "youngerpartners",
      externalId: "YP-DFW-004",
    },
    {
      address: "7600 N Lamar Blvd",
      city: "Austin",
      zip: "78752",
      lat: 30.3450,
      lng: -97.7170,
      market: "austin",
      propertyType: "Retail",
      listingType: "Sublease",
      buildingSf: 6500,
      priceAmount: 24,
      priceUnit: "per_sf_yr",
      yearBuilt: 2014,
      brokerName: "Karen White",
      brokerCompany: "Retail Solutions",
      description: "Former restaurant space on North Lamar. Full commercial kitchen, walk-in cooler, patio seating. Sublease through 2027 with renewal options.",
      imageUrl: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=600",
      sourceSlug: "crexi",
      externalId: "CX-AUS-004",
    },
    {
      address: "301 S Congress Ave",
      city: "Austin",
      zip: "78704",
      lat: 30.2570,
      lng: -97.7460,
      market: "austin",
      propertyType: "Retail",
      listingType: "Lease",
      buildingSf: 2100,
      priceAmount: 55,
      priceUnit: "per_sf_yr",
      yearBuilt: 2009,
      brokerName: "Sarah Mitchell",
      brokerCompany: "CBRE",
      description: "Iconic South Congress retail storefront. Prime foot traffic location between Jo's Coffee and Allen's Boots. Perfect for fashion, gifts, or food concept.",
      imageUrl: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=600",
      sourceSlug: "loopnet",
      externalId: "LN-AUS-005",
    },
    {
      address: "2000 E Randol Mill Rd",
      city: "Arlington",
      zip: "76011",
      lat: 32.7570,
      lng: -97.0780,
      market: "dfw",
      propertyType: "Hospitality",
      listingType: "Sale",
      buildingSf: 95000,
      lotSizeAcres: 3.8,
      priceAmount: 22000000,
      priceUnit: "total",
      yearBuilt: 2016,
      brokerName: "Paul Simmons",
      brokerCompany: "HFF",
      description: "175-key select-service hotel near AT&T Stadium and Globe Life Field. Strong RevPAR performance. Renovated in 2023. Franchise agreement through 2034.",
      imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600",
      sourceSlug: "crexi",
      externalId: "CX-DFW-003",
    },
  ];

  let created = 0;
  for (const l of listings) {
    const dedupeKey = [
      l.address.toLowerCase().replace(/\s+/g, " ").trim(),
      (l.buildingSf ?? 0).toString(),
      l.propertyType.toLowerCase(),
      (l.brokerName ?? "unknown").toLowerCase(),
    ].join("|");

    const listing = await prisma.listing.upsert({
      where: { dedupeKey },
      create: {
        address: l.address,
        city: l.city,
        state: "TX",
        zip: l.zip,
        lat: l.lat,
        lng: l.lng,
        market: l.market,
        propertyType: l.propertyType,
        listingType: l.listingType,
        buildingSf: l.buildingSf ?? null,
        lotSizeAcres: l.lotSizeAcres ?? null,
        priceAmount: l.priceAmount,
        priceUnit: l.priceUnit,
        yearBuilt: l.yearBuilt ?? null,
        brokerName: l.brokerName,
        brokerCompany: l.brokerCompany,
        description: l.description,
        imageUrl: l.imageUrl ?? null,
        dedupeKey,
      },
      update: {},
    });

    // Create variant
    await prisma.listingVariant.upsert({
      where: {
        sourceId_externalId: {
          sourceId: sourceMap[l.sourceSlug],
          externalId: l.externalId,
        },
      },
      create: {
        listingId: listing.id,
        sourceId: sourceMap[l.sourceSlug],
        externalId: l.externalId,
        sourceUrl: l.sourceUrl ?? null,
        priceAmount: l.priceAmount,
        priceUnit: l.priceUnit,
        buildingSf: l.buildingSf ?? null,
        description: l.description,
        brokerName: l.brokerName,
      },
      update: {},
    });

    created++;
    console.log(`  [${created}] ${l.address}, ${l.city} - ${l.propertyType} ${l.listingType}`);
  }

  console.log(`\nSeeded ${created} listings across Austin and DFW`);
  await (prisma as unknown as { $disconnect: () => Promise<void> }).$disconnect();
}

main().catch(console.error);
